on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: exelban/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: info
      - name: Test
        run: ls -al /tmp; go test -mod=vendor ./...
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
      - name: Coverage
        run: go test -mod=vendor -coverage ./...
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json